Repository superseriousbusiness/gotosocial, pull requests merged in 2022-12, with the labels that each got.

#1193 [bugfix] Profile grid scaling in webkit based browsers
  web/source/settings/style.css
Labels: frontend, chore

#1199 [frogend/bugfix] Remove domain block edit functionality until implemented in backend
  web/source/settings/admin/federation.js
Labels: bug, frontend

#1206 [docs] Remove filesystem logging directives from example systemd unit config
  docs/installation_guide/binary.md
  example/gotosocial.service
Labels: documentation

#1155 [feature] media: add webp support
  go.mod
  go.sum
  internal/api/client/instance/instancepatch_test.go
  internal/media/image.go
  internal/media/processingmedia.go
  internal/media/types.go
  internal/media/util.go
  vendor/github.com/superseriousbusiness/exif-terminator/jpeg.go
  vendor/github.com/superseriousbusiness/exif-terminator/terminator.go
  vendor/github.com/superseriousbusiness/exif-terminator/webp.go
  vendor/golang.org/x/image/riff/riff.go
  vendor/golang.org/x/image/vp8/decode.go
  vendor/golang.org/x/image/vp8/filter.go
  vendor/golang.org/x/image/vp8/idct.go
  vendor/golang.org/x/image/vp8/partition.go
  vendor/golang.org/x/image/vp8/pred.go
  vendor/golang.org/x/image/vp8/predfunc.go
  vendor/golang.org/x/image/vp8/quant.go
  vendor/golang.org/x/image/vp8/reconstruct.go
  vendor/golang.org/x/image/vp8/token.go
  vendor/golang.org/x/image/vp8l/decode.go
  vendor/golang.org/x/image/vp8l/huffman.go
  vendor/golang.org/x/image/vp8l/transform.go
  vendor/golang.org/x/image/webp/decode.go
  vendor/golang.org/x/image/webp/doc.go
  vendor/modules.txt
Labels: ready

#1246 [feature] support configuring database caches
  example/config.yaml
  internal/cache/gts.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/gen/gen.go
  internal/config/helpers.gen.go
  internal/config/state.go
  internal/config/testdata/test.yaml
  test/envparsing.sh
  testrig/config.go
Labels: ready

#1270 [frogend] Use match-sorter for filtering domain blocks
  web/source/settings/admin/federation.js
Labels: frontend
