Repository superseriousbusiness/gotosocial, pull requests merged in 2022-11, with the labels that each got.

#996 [chore] update gruf libraries
  go.mod
  go.sum
  vendor/codeberg.org/gruf/go-mutexes/map.go
  vendor/codeberg.org/gruf/go-mutexes/map_pool.go
  vendor/codeberg.org/gruf/go-store/v2/util/io.go
  vendor/modules.txt
Labels: performance, chore

#995 [feature] various worker / request queue improvements
  go.mod
  internal/concurrency/workers.go
  internal/httpclient/client.go
  internal/httpclient/queue.go
  internal/httpclient/queue_test.go
Labels: enhancement, performance, chore

#997 [chore/frontend] CI steps for frontend stuff
  .drone.yml
  web/source/.eslintignore
  web/source/package.json
  web/source/yarn.lock
Labels: frontend, chore

#1051 [frogend] Emoji categories
  web/source/css/base.css
  web/source/package.json
  web/source/settings/admin/emoji/new-emoji.js
  web/source/settings/admin/emoji/overview.js
  web/source/settings/components/combo-box.jsx
  web/source/settings/components/form/combobox.jsx
  web/source/settings/components/form/index.js
  web/source/settings/redux/reducers/user.js
  web/source/settings/style.css
  web/source/yarn.lock
Labels: frontend

#1130 [frogend] fix profile preview css, use role info
  web/source/css/profile.css
  web/source/settings/components/fake-profile.jsx
  web/source/settings/lib/api/oauth.js
  web/source/settings/style.css
  web/source/settings/user/profile.js
Labels: frontend, chore

#1182 [bugfix] Change page width to prevent scrollbar overflow
  web/source/css/base.css
Labels: frontend, chore
